-- Bootstrap migration: idempotent base-table creation for fresh databases.
-- Issue #535: `npm run db:migrate` could not bootstrap a fresh Neon branch
-- because the runner skips drizzle-kit baseline files matching /^\d{4}_/ and
-- all three core tables (users/sessions/thoughts) only exist in the excluded
-- 0000_romantic_night_nurse.sql.
--
-- Filename convention: a single leading digit + underscore sorts before all
-- letter-prefixed filenames under a plain lexicographic `.sort()`, yet is NOT
-- matched by the /^\d{4}_/ exclusion (which requires exactly 4 digits), so the
-- runner includes this file and executes it first.
--
-- Related: #316 (e2e ephemeral-branch plan relies on db:migrate for fresh DBs).
--
-- Local dev preferred path: npx drizzle-kit push (introspects schema.ts).
-- Ledgered bootstrap path (CI, Vercel, e2e): npm run db:migrate (this file
-- runs first, then all *_incremental.sql files run in their existing
-- lexicographic order and find their prerequisites in place).
--
-- IDEMPOTENCY: Every statement uses IF NOT EXISTS or a DO $$ existence guard so
-- that on prod/preview (where all objects already exist) this file is a pure
-- no-op that records exactly one new schema_migrations ledger row.
--
-- ORDERING HAZARD COVERAGE: buddy_session_participants_one_host_per_session_incremental.sql
-- and buddy_session_participants_user_index_incremental.sql sort before
-- buddy_sessions_incremental.sql (which creates the tables they index). This
-- file creates buddy_sessions and buddy_session_participants with their full
-- current definitions so those index files run cleanly; the subsequent
-- CREATE TABLE IF NOT EXISTS in buddy_sessions_incremental.sql is a no-op.
--
-- APPEND-ONLY: Do not edit this file after it is applied (checksum ledger rule;
-- see drizzle/README.md and incidents #368/#370). Future base-table additions
-- belong in new idempotent incremental files, not edits here.

-- ============================================================
-- 1. users (base-only: no *_incremental.sql recreates this table)
--    Base column set from 0000_romantic_night_nurse.sql. Later incrementals
--    backfill additional columns via ADD COLUMN IF NOT EXISTS.
-- ============================================================
CREATE TABLE IF NOT EXISTS "users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "email" varchar(255) NOT NULL,
  "username" varchar(50) NOT NULL,
  "password_hash" varchar(255),
  "is_public" boolean DEFAULT false NOT NULL,
  "current_day" integer DEFAULT 1 NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "users_email_unique" UNIQUE("email")
);

CREATE INDEX IF NOT EXISTS "idx_users_public"
  ON "users" USING btree ("is_public");

-- Case-insensitive username uniqueness (issue #8). users_uniqueness_incremental.sql
-- also creates this index via IF NOT EXISTS (no-op on a fresh DB after this file).
CREATE UNIQUE INDEX IF NOT EXISTS "users_username_lower_unique"
  ON "users" USING btree (lower("username"));

-- ============================================================
-- 2. sessions (base-only: no *_incremental.sql recreates this table)
--    Base column set from 0000 baseline, including buddy_session_id column
--    (nullable; the FK to buddy_sessions and the buddy-related indexes are
--    owned by sessions_buddy_session_id_incremental.sql and must not be
--    duplicated here).
-- ============================================================
CREATE TABLE IF NOT EXISTS "sessions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "buddy_session_id" uuid,
  "day_number" integer NOT NULL,
  "session_type" varchar(20) DEFAULT 'standard' NOT NULL,
  "duration" integer NOT NULL,
  "completed" boolean NOT NULL,
  "actual_time" integer,
  "clear_percent" integer NOT NULL,
  "thought_count" integer DEFAULT 0 NOT NULL,
  "mind_state_log" jsonb,
  "session_date" date NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "sessions_session_type_allowed" CHECK ("session_type" in ('standard', 'quick'))
);

-- FK: sessions.user_id -> users.id
-- (sessions_session_type_incremental.sql adds the column + CHECK constraint via
--  ADD COLUMN IF NOT EXISTS / DO $$ guard; both are no-ops when the table already
--  has them from this file.)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sessions_user_id_users_id_fk'
  ) THEN
    ALTER TABLE "sessions"
      ADD CONSTRAINT "sessions_user_id_users_id_fk"
      FOREIGN KEY ("user_id") REFERENCES "public"."users"("id")
      ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_sessions_user"
  ON "sessions" USING btree ("user_id", "day_number");

-- NOTE: sessions_buddy_session_id_buddy_sessions_id_fk, idx_sessions_buddy_session,
-- and sessions_user_buddy_session_unique are intentionally omitted — they are
-- owned by sessions_buddy_session_id_incremental.sql, which guards them with
-- DO $$ / IF NOT EXISTS and runs after buddy_sessions exists.

-- ============================================================
-- 3. thoughts (base-only: no *_incremental.sql recreates this table)
--    Full column set from 0000 baseline (no later incrementals alter this table).
-- ============================================================
CREATE TABLE IF NOT EXISTS "thoughts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "session_id" uuid NOT NULL,
  "day_number" integer NOT NULL,
  "time_in_session" integer NOT NULL,
  "text" varchar(1000) NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'thoughts_user_id_users_id_fk'
  ) THEN
    ALTER TABLE "thoughts"
      ADD CONSTRAINT "thoughts_user_id_users_id_fk"
      FOREIGN KEY ("user_id") REFERENCES "public"."users"("id")
      ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'thoughts_session_id_sessions_id_fk'
  ) THEN
    ALTER TABLE "thoughts"
      ADD CONSTRAINT "thoughts_session_id_sessions_id_fk"
      FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id")
      ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_thoughts_user"
  ON "thoughts" USING btree ("user_id", "day_number");

-- ============================================================
-- 4. buddy_sessions (full current definition — ordering hazard fix)
--    buddy_session_participants_one_host_per_session_incremental.sql and
--    buddy_session_participants_user_index_incremental.sql sort before
--    buddy_sessions_incremental.sql (which creates this table) but create
--    indexes on buddy_session_participants. Both tables must exist before
--    those index files run. Full definition (including scheduled_start_at,
--    daily_room_name, daily_room_url) is used so that later ALTER TABLE ADD
--    COLUMN IF NOT EXISTS from buddy_sessions_v2_daily_room_incremental.sql
--    and partner_scheduling_google_calendar_incremental.sql are no-ops.
-- ============================================================
CREATE TABLE IF NOT EXISTS "buddy_sessions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "share_token" varchar(48) NOT NULL,
  "host_user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "state" varchar(20) NOT NULL DEFAULT 'waiting',
  "duration_seconds" integer NOT NULL,
  "scheduled_start_at" timestamp with time zone,
  "started_at" timestamp with time zone,
  "daily_room_name" varchar(128),
  "daily_room_url" text,
  "revision" integer NOT NULL DEFAULT 0,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "buddy_sessions_share_token_unique" UNIQUE("share_token"),
  CONSTRAINT "buddy_sessions_state_allowed" CHECK (
    "state" IN ('waiting', 'ready_check', 'active', 'completed', 'abandoned')
  )
);

CREATE INDEX IF NOT EXISTS "idx_buddy_sessions_host"
  ON "buddy_sessions" ("host_user_id");

-- ============================================================
-- 5. buddy_session_participants (full current definition — ordering hazard fix)
--    Same ordering hazard as buddy_sessions above. Full definition used so
--    that buddy_sessions_incremental.sql CREATE TABLE IF NOT EXISTS is a no-op
--    and any later column additions would also be no-ops if needed.
-- ============================================================
CREATE TABLE IF NOT EXISTS "buddy_session_participants" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "buddy_session_id" uuid NOT NULL REFERENCES "buddy_sessions"("id") ON DELETE CASCADE,
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "is_host" boolean NOT NULL DEFAULT false,
  "ready" boolean NOT NULL DEFAULT false,
  "joined_at" timestamp with time zone NOT NULL DEFAULT now(),
  "last_seen_at" timestamp with time zone NOT NULL DEFAULT now(),
  "left_at" timestamp with time zone,
  "participant_completed_at" timestamp with time zone,
  CONSTRAINT "buddy_session_participants_session_user" UNIQUE ("buddy_session_id", "user_id")
);
